// Chrome runs chrome.i18n.detectLanguage()'s callback synchronously, and the
// popup reads the result right after the call to pick the date-fns locale for
// library rows. Firefox calls back asynchronously (so the popup always falls
// back to US English dates) and its detector answers differently anyway.
// The popup only ever passes its own "nomatch_no_audio" message, so answer
// those texts synchronously with Chrome's results.
(() => {
  // Text -> [isReliable, language], generated by build.py from _locales.
  const CHROME_RESULTS = __CHROME_DETECT_RESULTS__;
  const i18n = chrome.i18n;
  const nativeDetect = i18n.detectLanguage.bind(i18n);
  i18n.detectLanguage = (text, callback) => {
    const known = CHROME_RESULTS[text];
    if (!known || typeof callback !== "function") return nativeDetect(text, callback);
    const [isReliable, language] = known;
    callback({ isReliable, languages: [{ language, percentage: 100 }] });
    return undefined;
  };
})();
